name: setup-nexus-npm
inputs:
  username:
    required: true
  password:
    required: true
runs:
  using: composite
  steps:
    - run: |
        cat << EOF > ~/.npmrc
        registry=https://nexus.txm.tools/repository/npm/
        @txm:registry=https://nexus.txm.tools/repository/npm-txm/
        _auth=$(echo -n ${{ inputs.username }}:${{ inputs.password }} | base64)
        EOF
      shell: bash
      