name: setup-nexus-npm
inputs:
  endpoint:
    required: true
  login:
    required: true
  password:
    required: true
runs:
  using: composite
  steps:
    - run: |
        rm -f ~/.npmrc
        echo registry=https://${{ inputs.endpoint }}/repository/npm-txm >> ~/.npmrc
        echo _auth=$(echo -n ${{ inputs.login }}:${{ inputs.password }} | base64) >> ~/.npmrc
        source ~/.npmrc
      shell: bash
