name: npm-version-tag
inputs:
  version:
    required: true
runs:
  using: composite
  steps:
    - run: |
        npm version ${{ inputs.version }}
        echo "NPM version successfully updated"
        git push origin $GITHUB_BASE_REF
        git push origin --tags
        echo "pushed new version tag: $NEW_VERSION_TAG to repo"        
      shell: bash
