name: 'major version tag'
description: 'return the major version for a given full version'
inputs:
  version:
    required: true
outputs:
  major_version:
    description: 'major version of the provided full version'
    value: ${{ steps.set-major-version.outputs.major_version }}
runs:
  using: 'composite'
  steps:
    - id: set-major-version
      run: |
        version=${{ inputs.version }}
        MAJOR_VERSION=(${version//./ })
        echo "major version is $MAJOR_VERSION"
        echo "::set-output name=major_version::$MAJOR_VERSION"
      shell: bash
