name: 'major version tag'
description: 'return the major version for a given full version'
inputs:
  version:
    required: true
outputs:
  major_version:
    description: 'major version of the provided full version'
    value: ${{ steps.set-major-version.outputs.major_version }}
runs:
  using: 'composite'
  steps:
    - id: set-major-version
      run: |
        version=${{ inputs.version }}
        MAJOR_VERSION=(${version//./ })
        echo "major version is $MAJOR_VERSION"
        echo "major_version=$MAJOR_VERSION" >> $GITHUB_OUTPUT
        if [[ -z "${GITHUB_OUTPUT}" ]]; then echo "GITHUB_OUTPUT zero length or unset! Aborting"; exit 1; fi
      shell: bash
