name: setup-nexus-go
inputs:
  endpoint:
    required: true
  login:
    required: true
  password:
    required: true
runs:
  using: composite
  steps:
    - run: |
        echo GONOSUMDB=github.com/sportsball-ai >> $GITHUB_ENV
        echo GOPROXY=https://${{ inputs.endpoint }}/repository/go >> $GITHUB_ENV
        echo GOSUMDB="sum.golang.org https://${{ inputs.endpoint }}/repository/gosumdb" >> $GITHUB_ENV
        rm -f ~/.netrc
        echo machine ${{ inputs.endpoint }} >> ~/.netrc
        echo login ${{ inputs.login }} >> ~/.netrc
        echo password ${{  inputs.password }} >> ~/.netrc
      shell: bash
