name: setup-nexus-go
inputs:
  endpoint:
    required: true
  version:
    required: true
  login:
    required: true
  password:
    required: true
runs:
  using: composite
  steps:
    - run: |
        export GONOSUMDB=github.com/sportsball-ai
        export GOPROXY=https://${{ inputs.endpoint }}/repository/go
        export GOSUMDB="sum.golang.org https://${{ inputs.endpoint }}/repository/gosumdb"
        rm -f ~/.netrc
        echo machine ${{ inputs.endpoint }} >> ~/.netrc
        echo login ${{ inputs.login }} >> ~/.netrc
        echo password ${{  inputs.password }} >> ~/.netrc
      shell: bash
